const STORE={products:[],cart:[],saved:[]};
const $=(s,r=document)=>r.querySelector(s); const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n);
async function init(){try{STORE.products=await fetch('data/catalog.json').then(r=>r.json())}catch(e){console.error(e);STORE.products=[]}
 STORE.cart=JSON.parse(localStorage.getItem('paperloop-cart')||'[]'); STORE.saved=JSON.parse(localStorage.getItem('paperloop-saved')||'[]');
 bindNav(); bindCart(); bindNewsletter(); bindForms(); renderHome(); renderShop(); renderProduct(); updateCart();
}
function save(){localStorage.setItem('paperloop-cart',JSON.stringify(STORE.cart));localStorage.setItem('paperloop-saved',JSON.stringify(STORE.saved));}
function toast(m){const t=$('[data-toast]');if(!t)return;t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
function bindNav(){$('[data-menu]')?.addEventListener('click',()=> $('[data-nav]')?.classList.toggle('open'))}
function productCard(p){const saved=STORE.saved.includes(p.id);return `<article class="product-card"><div class="product-image"><img src="assets/images/products/${p.image}" alt="${p.name}" loading="lazy"><span class="tag">${p.tag}</span><button class="heart" data-save="${p.id}" aria-label="Save ${p.name}">${saved?'♥':'♡'}</button></div><div class="product-body"><small>${p.category}</small><h3>${p.name}</h3><div class="price"><strong>${money(p.price)}</strong><del>${money(p.old)}</del></div><div class="card-actions"><a class="btn outline" href="product.html?id=${p.id}">View</a><button class="btn primary" data-add="${p.id}">Add</button></div></div></article>`}
function bindProductButtons(root=document){$$('[data-add]',root).forEach(b=>b.onclick=()=>addToCart(b.dataset.add));$$('[data-save]',root).forEach(b=>b.onclick=()=>toggleSave(b.dataset.save));}
function renderHome(){const box=$('[data-featured]');if(!box)return;box.innerHTML=STORE.products.slice(0,8).map(productCard).join('');bindProductButtons(box)}
function renderShop(){const grid=$('[data-shop-grid]');if(!grid)return;const search=$('[data-search]'), filter=$('[data-filter]'), sort=$('[data-sort]');const cats=[...new Set(STORE.products.map(p=>p.category))];filter.innerHTML='<option value="all">All categories</option>'+cats.map(c=>`<option>${c}</option>`).join('');const params=new URLSearchParams(location.search);if(params.get('cat'))filter.value=params.get('cat');if(params.get('q'))search.value=params.get('q');function apply(){let arr=[...STORE.products],q=(search.value||'').toLowerCase(),cat=filter.value;arr=arr.filter(p=>(!q||(p.name+' '+p.category+' '+p.desc).toLowerCase().includes(q))&&(cat==='all'||p.category===cat));if(sort.value==='low')arr.sort((a,b)=>a.price-b.price);if(sort.value==='high')arr.sort((a,b)=>b.price-a.price);if(sort.value==='name')arr.sort((a,b)=>a.name.localeCompare(b.name));grid.innerHTML=arr.map(productCard).join('');$('[data-empty]').hidden=arr.length>0;bindProductButtons(grid)}search.oninput=apply;filter.onchange=apply;sort.onchange=apply;apply()}
function renderProduct(){const id=new URLSearchParams(location.search).get('id');const p=STORE.products.find(x=>x.id===id);if(!p)return;document.title=p.name+' — PAPERLOOP';$('[data-detail-image]').src='assets/images/products/'+p.image;$('[data-detail-image]').alt=p.name;$('[data-detail-category]').textContent=p.category;$('[data-detail-name]').textContent=p.name;$('[data-detail-price]').textContent=money(p.price);$('[data-detail-old]').textContent=money(p.old);$('[data-detail-desc]').textContent=p.desc;$('[data-detail-add]').onclick=()=>addToCart(p.id);$('[data-detail-save]').onclick=()=>toggleSave(p.id);const rel=STORE.products.filter(x=>x.id!==p.id&&x.category===p.category).slice(0,4);$('[data-related]').innerHTML=(rel.length?rel:STORE.products.filter(x=>x.id!==p.id).slice(0,4)).map(productCard).join('');bindProductButtons($('[data-related]'))}
function addToCart(id){const p=STORE.products.find(x=>x.id===id),row=STORE.cart.find(x=>x.id===id);if(!p)return;if(row)row.qty++;else STORE.cart.push({id,qty:1});save();updateCart();toast(p.name+' added to cart')}
function changeQty(id,d){const row=STORE.cart.find(x=>x.id===id);if(!row)return;row.qty+=d;if(row.qty<=0)STORE.cart=STORE.cart.filter(x=>x.id!==id);save();updateCart()}
function updateCart(){const count=STORE.cart.reduce((s,x)=>s+x.qty,0);$$('[data-cart-count]').forEach(x=>x.textContent=count);const box=$('[data-cart-items]');if(!box)return;if(!STORE.cart.length){box.innerHTML='<div class="empty">Your cart is empty.</div>'}else{box.innerHTML=STORE.cart.map(r=>{const p=STORE.products.find(x=>x.id===r.id);return `<div class="cart-row"><img src="assets/images/products/${p.image}" alt=""><div><b>${p.name}</b><div class="qty"><button data-minus="${p.id}">−</button><span>${r.qty}</span><button data-plus="${p.id}">+</button></div></div><strong>${money(p.price*r.qty)}</strong></div>`}).join('');$$('[data-minus]').forEach(b=>b.onclick=()=>changeQty(b.dataset.minus,-1));$$('[data-plus]').forEach(b=>b.onclick=()=>changeQty(b.dataset.plus,1))}const total=STORE.cart.reduce((s,r)=>{const p=STORE.products.find(x=>x.id===r.id);return s+p.price*r.qty},0);$('[data-cart-total]').textContent=money(total)}
function bindCart(){$('[data-cart-open]')?.addEventListener('click',()=> $('[data-cart]')?.classList.add('open'));$('[data-cart-close]')?.addEventListener('click',()=> $('[data-cart]')?.classList.remove('open'));$('[data-demo-checkout]')?.addEventListener('click',()=>toast('Demo checkout — no payment was processed.'))}
function toggleSave(id){const p=STORE.products.find(x=>x.id===id);if(STORE.saved.includes(id)){STORE.saved=STORE.saved.filter(x=>x!==id);toast('Removed from wishlist')}else{STORE.saved.push(id);toast('Saved to wishlist')}save();renderHome();renderShop();renderProduct()}
function bindNewsletter(){$('[data-newsletter]')?.addEventListener('submit',e=>{e.preventDefault();toast('Thanks — demo signup received. Nothing was sent.')})}
function bindForms(){$('[data-demo-form]')?.addEventListener('submit',e=>{e.preventDefault();const s=$('[data-form-status]');if(s)s.textContent='Demo only — nothing was transmitted.';toast('Demo message prepared.')})}
init();